=== DaniSeguraDAW/XML/pack4/institut.dtd
<!ELEMENT llistacursos (curs+)>
<!ELEMENT curs (alumnes)>
<!ELEMENT alumnes (alumne+)>
<!ELEMENT alumne (dni, nom, cognom, cognom2?, assignatures)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT cognom2 (#PCDATA)>
<!ELEMENT assignatures (assignatura+)>
<!ELEMENT assignatura (nom, professor)>
<!ELEMENT professor (nrp, nom, cognom, cognom2?)>
<!ELEMENT nrp (#PCDATA)>
<!ATTLIST assignatura codi CDATA #REQUIRED>

=== DaniSeguraDAW/XML/pack4/institiut.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistacursos SYSTEM "institut.dtd">
<llistacursos>
    <curs>
        <alumnes>
            <alumne>
                <dni>12345678A</dni>
                <nom>Joan</nom>
                <cognom>Marí</cognom>
                <cognom2>Martínez</cognom2>
                <assignatures>
                    <assignatura codi="MAT101">
                        <nom>Matemàtiques</nom>
                        <professor>
                            <nrp>987654321</nrp>
                            <nom>Marta</nom>
                            <cognom>Garcia</cognom>
                        </professor>
                    </assignatura>
                    <assignatura codi="CAT102">
                        <nom>Català</nom>
                        <professor>
                            <nrp>123456789</nrp>
                            <nom>Pere</nom>
                            <cognom>Vidal</cognom>
                        </professor>
                    </assignatura>
                </assignatures>
            </alumne>
        </alumnes>
    </curs>
</llistacursos>
